### ISSUE TITLE
0 -> vortex

### ISSUE THREAD

**Issue by robert3005** [fulcrum-so/vortex#88]
- [x] new name fulcrum-so/spiral#786 
- [x] ser/de
- [x] LICENSE file/headers
- [x] CI badges
- [ ] Cargo publish
---------
- usage
    - [ ] datafusion integration
    - [ ] spiral integration
- basic recursive compression that has no known correctness issues and doesn't obviously explode
    - [ ] (Optional) fulcrum-so/vortex#18
    - [x] fulcrum-so/vortex#26
    - [x] (Optional) fulcrum-so/vortex#20 
    - [X] fulcrum-so/spiral#884 
    - [X] fulcrum-so/spiral#887
- blog post
- more encodings
    - [x] (Optional) fulcrum-so/vortex#8 
    - [ ] (Optional) fulcrum-so/vortex#9 
    - [ ] (Optional) fulcrum-so/vortex#10

**Comment by robert3005** [comment]
I think this issue outlived its usefulness. I will create separate issues for things that still matter - cargo publish and explore data fusion integration
